models:
  classification:
    - Logistic Regression
    - Random Forest Classifier
    - XGBoost Classifier
  regression:
    - Linear Regression
    - Random Forest Regressor
    - XGBoost Regressor
  clustering:
    - KMeans
    - DBSCAN

hyperparameters:
  random_forest:
    n_estimators: [100, 200, 300]
    max_depth: [10, 20, None]
  xgboost:
    n_estimators: [100, 200]
    learning_rate: [0.01, 0.1, 0.3]
